version: '3'

services:
  indigo_database:
    container_name: indigodb
    image: postgres:16.1
    environment:
      POSTGRES_DB: indigodb
      POSTGRES_PASSWORD: indigo
    ports:
      - "5432:5432"
    networks:
      - indigo_network
    restart: unless-stopped

  indigo_backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - indigo_database
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://indigo_database:5432/indigodb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: indigo
    networks:
      - indigo_network
    restart: unless-stopped


  indigo_frontend:
    build:
      context: ../../team-indigo-front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - indigo_network
    depends_on:
      - indigo_backend
    restart: unless-stopped


networks:
  indigo_network:
    driver: bridge


